accent = "#ff6f59"
cursor = "#d7dedc"
foreground = "#d7dedc"
background = "#191716"
selection_foreground = "#d7dedc"
selection_background = "#ff6f59"
color0 = "#2a2726"
color1 = "#ff6f59"
color2 = "#7d9d88"
color3 = "#d4a574"
color4 = "#8b7d7b"
color5 = "#c97b7b"
color6 = "#9a8b89"
color7 = "#d7dedc"
color8 = "#4a4240"
color9 = "#ff8a75"
color10 = "#95b39e"
color11 = "#e6b88a"
color12 = "#a39390"
color13 = "#e09191"
color14 = "#b0a19f"
color15 = "#e8efed"