accent = "#89b4fa"
cursor = "#d7dedc"
foreground = "#d7dedc"
background = "#191716"
selection_foreground = "#d7dedc"
selection_background = "#89b4fa"
color0 = "#45475a"
color1 = "#ff6f59"
color2 = "#a6e3a1"
color3 = "#f9e2af"
color4 = "#89b4fa"
color5 = "#f5c2e7"
color6 = "#94e2d5"
color7 = "#d7dedc"
color8 = "#585b70"
color9 = "#f38ba8"
color10 = "#a6e3a1"
color11 = "#f9e2af"
color12 = "#89b4fa"
color13 = "#f5c2e7"
color14 = "#94e2d5"
color15 = "#a6adc8"